//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderManagment_InventoryManagment_Entity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string ISBN { get; set; }
        public int CustomerID { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
        public virtual Book Book { get; set; }
    }
}
